version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=doc
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=123
      # Password for root access
      - MYSQL_ROOT_PASSWORD=123
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3308:3306
    volumes:
      - doc:/var/lib/mysql
  # Names our volume
volumes:
  doc: